# Generated by Django 5.0.4 on 2024-05-07 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0005_auteur'),
    ]

    operations = [
        migrations.AddField(
            model_name='livre',
            name='auteur',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sites.auteur'),
            preserve_default=False,
        ),
    ]
