# Generated by Django 5.0.4 on 2024-05-08 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0006_livre_auteur'),
    ]

    operations = [
        migrations.AddField(
            model_name='auteur',
            name='desc',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auteur',
            name='image',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
