# Generated by Django 5.0.4 on 2024-05-10 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0007_auteur_desc_auteur_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auteur',
            name='image',
        ),
    ]
