# Generated by Django 5.0.4 on 2024-05-10 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0008_remove_auteur_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livre',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='livre',
            name='updated_at',
        ),
        migrations.DeleteModel(
            name='Article',
        ),
    ]
